version: '3.9'

services:
  web:
    build: 
      context: .

    # command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:alpine
    command: redis-server

    ports:
      - '6379:6379'

