version: '3.9'

services: 
  redis:
    image: redis:alpine
    command: redis-server 
    ports:
      - 6379:6379

      
  web:
    build: 
      context: .
    environment:
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    depends_on:
      - redis
    links:
      - redis

