version: '3.9'

services: 
  redis:
    image: redis:alpine
    command: redis-server

    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./data:/data
      
  web:
    build: 
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    volumes:
      - .:/code/
    # command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis
    links:
      - redis



 
      

